using System.Data;
using System.Data.SqlClient;

namespace SMART
{

public sealed partial class CalendarControl : UserControl
{
    private static readonly Color BgColor = Color.FromArgb(13, 17, 38);
    private static readonly Color CardColor = Color.FromArgb(22, 33, 62);
    private static readonly Color AccentColor = Color.FromArgb(233, 69, 96);
    private static readonly Color TextGray = Color.FromArgb(150, 150, 170);
    private static readonly Color DimGray = Color.FromArgb(85, 85, 119);
    private readonly string employeeId;
    private readonly string instructorName;
    private readonly List<(int Id, string Title)> courses;
    private DateTime displayedMonth = new(DateTime.Today.Year, DateTime.Today.Month, 1);
    private Dictionary<DateTime, List<CalendarEvent>> eventsByDate = new();
    private int? selectedEventId;
    private readonly Dictionary<CustomPanel, (Color BackColor, Color BorderColor, int BorderWidth)> dayCellStyles = new();

    private sealed record CalendarEvent(int Id, string Title, DateTime Date, string Type,
        int? CourseId, bool AutoGenerated, string? Description, string? OwnerEmployeeId);

    public CalendarControl()
    {
        InitializeComponent();
        employeeId = "";
        instructorName = "";
        courses = new List<(int Id, string Title)>();
        eventType.SelectedIndex = 5;
        coursePicker.Items.Add(new CourseChoice(null, "None"));
        coursePicker.SelectedIndex = 0;
    }

    public CalendarControl(string employeeId, string instructorName, List<(int Id, string Title)> courses)
        : this()
    {
        this.employeeId = employeeId;
        this.instructorName = instructorName;
        this.courses = courses;
        AccessibleDescription = "Academic calendar for " + instructorName;
        foreach (var course in courses)
            coursePicker.Items.Add(new CourseChoice(course.Id, course.Title));
    }

    private void CalendarControl_Load(object? sender, EventArgs e)
    {
        if (System.ComponentModel.LicenseManager.UsageMode == System.ComponentModel.LicenseUsageMode.Designtime ||
            DesignMode || string.IsNullOrEmpty(employeeId)) return;
        LoadEvents();
    }

    private void Previous_Click(object? sender, EventArgs e)
    {
        displayedMonth = displayedMonth.AddMonths(-1);
        LoadEvents();
    }

    private void Next_Click(object? sender, EventArgs e)
    {
        displayedMonth = displayedMonth.AddMonths(1);
        LoadEvents();
    }

    private void AddButton_Click(object? sender, EventArgs e) => AddEvent();

    private void DeleteButton_Click(object? sender, EventArgs e) => DeleteSelectedEvent();

    private void LoadEvents()
    {
        monthLabel.Text = displayedMonth.ToString("MMMM yyyy");
        try
        {
            eventsByDate = new Dictionary<DateTime, List<CalendarEvent>>();
            using var connection = OpenConnection();
            using var command = new SqlCommand(@"SELECT EventId, Title, EventDate, EventType,
                    CourseId, IsAutoGenerated, Description, InstructorEmployeeID
                FROM dbo.Events
                WHERE (InstructorEmployeeID = @empId OR InstructorEmployeeID IS NULL)
                    AND YEAR(EventDate) = @year AND MONTH(EventDate) = @month
                ORDER BY EventDate, Title", connection);
            command.Parameters.Add("@empId", SqlDbType.NVarChar, 50).Value = employeeId;
            command.Parameters.Add("@year", SqlDbType.Int).Value = displayedMonth.Year;
            command.Parameters.Add("@month", SqlDbType.Int).Value = displayedMonth.Month;
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                var item = new CalendarEvent(reader.GetInt32(0), reader.GetString(1), reader.GetDateTime(2),
                    reader.GetString(3), reader.IsDBNull(4) ? null : reader.GetInt32(4),
                    reader.GetBoolean(5), reader.IsDBNull(6) ? null : reader.GetString(6),
                    reader.IsDBNull(7) ? null : reader.GetString(7));
                if (!eventsByDate.TryGetValue(item.Date.Date, out var dayEvents))
                    eventsByDate[item.Date.Date] = dayEvents = new List<CalendarEvent>();
                dayEvents.Add(item);
            }
            message.Text = "";
        }
        catch (SqlException ex)
        {
            eventsByDate.Clear();
            message.Text = "Calendar could not load: " + ex.Message;
            message.ForeColor = AccentColor;
        }
        DrawCalendar();
    }

    private void DrawCalendar()
    {
        DateTime start = displayedMonth.AddDays(-(int)displayedMonth.DayOfWeek);
        for (int i = 0; i < 42; i++)
        {
            DateTime date = start.AddDays(i);
            var cell = (CustomPanel)calendarGrid.GetControlFromPosition(i % 7, i / 7 + 1)!;
            var dayNumber = cell.Controls.OfType<Label>().Single();
            var eventList = cell.Controls.OfType<FlowLayoutPanel>().Single();
            if (!dayCellStyles.TryGetValue(cell, out var style))
                dayCellStyles[cell] = style = (cell.BackColor, cell.BorderColor, cell.BorderWidth);
            cell.Tag = dayNumber.Tag = date;
            dayNumber.Text = date.Day.ToString();
            dayNumber.ForeColor = date.Month == displayedMonth.Month ? Color.White : DimGray;
            cell.BackColor = style.BackColor;
            cell.BorderColor = style.BorderColor;
            cell.BorderWidth = style.BorderWidth;
            if (date.Date == DateTime.Today)
            {
                cell.BackColor = Color.FromArgb(60, 30, 50);
                cell.BorderColor = AccentColor;
                cell.BorderWidth = 2;
            }
            eventsByDate.TryGetValue(date.Date, out var dayEvents);
            var chips = eventList.Controls.OfType<CustomButton>().ToArray();
            for (int slot = 0; slot < chips.Length; slot++)
            {
                var chip = chips[slot];
                var ev = dayEvents != null && slot < dayEvents.Count ? dayEvents[slot] : null;
                chip.Visible = ev != null;
                chip.Tag = ev;
                if (ev == null) continue;
                chip.Text = ev.Title;
                chip.BackColor = ColorForEventType(ev.Type);
                chip.Width = Math.Max(35, eventList.ClientSize.Width - 2);
            }
            var more = eventList.Controls.OfType<Label>().Single();
            more.Tag = date;
            more.Visible = dayEvents?.Count > chips.Length;
            more.Text = $"+{Math.Max(0, (dayEvents?.Count ?? 0) - chips.Length)} more";
        }
    }

    private void DayCell_Click(object? sender, EventArgs e)
    {
        DateTime date = sender switch
        {
            Control { Tag: DateTime taggedDate } => taggedDate,
            Control { Parent: Control { Tag: DateTime parentDate } } => parentDate,
            _ => eventDate.Value.Date
        };
        eventDate.Value = date;
        if (date.Month != displayedMonth.Month || date.Year != displayedMonth.Year)
        {
            displayedMonth = new DateTime(date.Year, date.Month, 1);
            LoadEvents();
        }
        selectedEventId = null;
        deleteButton.Enabled = false;
        message.Text = eventsByDate.TryGetValue(date.Date, out var dayEvents)
            ? string.Join(" · ", dayEvents.Select(item => item.Title)) : "Selected " + date.ToString("MMM d");
        message.ForeColor = TextGray;
    }

    private void EventChip_Click(object? sender, EventArgs e)
    {
        if (sender is not Control { Tag: CalendarEvent ev }) return;
        eventDate.Value = ev.Date;
        titleInput.Text = ev.Title;
        descriptionInput.Text = ev.Description ?? "";
        eventType.SelectedItem = NormalizeEventType(ev.Type);
        selectedEventId = ev.Id;
        deleteButton.Enabled = !ev.AutoGenerated && ev.Type != "Holiday" && IsOwnedByInstructor(ev.Id);
        message.Text = deleteButton.Enabled ? "Selected event." : "Auto-generated events cannot be deleted.";
        message.ForeColor = TextGray;
    }

    private bool IsOwnedByInstructor(int eventId)
    {
        var ev = eventsByDate.Values.SelectMany(value => value).FirstOrDefault(item => item.Id == eventId);
        return ev != null && !ev.AutoGenerated &&
            string.Equals(ev.OwnerEmployeeId, employeeId, StringComparison.OrdinalIgnoreCase);
    }

    private void AddEvent()
    {
        string title = titleInput.Text.Trim();
        string description = descriptionInput.Text.Trim();
        if (title.Length == 0 || title.Length > 200)
        {
            ShowMessage("Enter a title of 1 to 200 characters.", true);
            return;
        }
        if (description.Length > 500)
        {
            ShowMessage("Description must be 500 characters or fewer.", true);
            return;
        }
        try
        {
            using var connection = OpenConnection();
            using var command = new SqlCommand(@"INSERT INTO dbo.Events
                    (Title, Description, EventDate, EventType, CourseId, InstructorEmployeeID, IsAutoGenerated)
                VALUES (@title, @desc, @date, @type, @courseId, @empId, 0)", connection);
            command.Parameters.Add("@title", SqlDbType.NVarChar, 200).Value = title;
            command.Parameters.Add("@desc", SqlDbType.NVarChar, 500).Value = string.IsNullOrWhiteSpace(description) ? DBNull.Value : description;
            command.Parameters.Add("@date", SqlDbType.Date).Value = eventDate.Value.Date;
            command.Parameters.Add("@type", SqlDbType.NVarChar, 50).Value = eventType.SelectedItem?.ToString() ?? "Other";
            int? courseId = (coursePicker.SelectedItem as CourseChoice)?.Id;
            command.Parameters.Add("@courseId", SqlDbType.Int).Value = courseId.HasValue ? courseId.Value : DBNull.Value;
            command.Parameters.Add("@empId", SqlDbType.NVarChar, 50).Value = employeeId;
            command.ExecuteNonQuery();
            titleInput.Text = "";
            descriptionInput.Text = "";
            selectedEventId = null;
            deleteButton.Enabled = false;
            if (eventDate.Value.Month != displayedMonth.Month || eventDate.Value.Year != displayedMonth.Year)
                displayedMonth = new DateTime(eventDate.Value.Year, eventDate.Value.Month, 1);
            LoadEvents();
            ShowMessage("Event added.", false);
        }
        catch (SqlException ex) { ShowMessage("Could not add event: " + ex.Message, true); }
    }

    private void DeleteSelectedEvent()
    {
        if (!selectedEventId.HasValue) return;
        try
        {
            using var connection = OpenConnection();
            using var command = new SqlCommand(@"DELETE FROM dbo.Events
                WHERE EventId = @id AND IsAutoGenerated = 0 AND InstructorEmployeeID = @empId", connection);
            command.Parameters.Add("@id", SqlDbType.Int).Value = selectedEventId.Value;
            command.Parameters.Add("@empId", SqlDbType.NVarChar, 50).Value = employeeId;
            if (command.ExecuteNonQuery() == 0)
            {
                ShowMessage("Only your own manual events can be deleted.", true);
                return;
            }
            selectedEventId = null;
            deleteButton.Enabled = false;
            LoadEvents();
            ShowMessage("Event deleted.", false);
        }
        catch (SqlException ex) { ShowMessage("Could not delete event: " + ex.Message, true); }
    }

    private static Color ColorForEventType(string? type) => type?.Replace(" ", "", StringComparison.Ordinal).ToLowerInvariant() switch
    {
        "holiday" => Color.FromArgb(204, 34, 68),
        "exam" => Color.FromArgb(106, 13, 173),
        "quiz" => Color.FromArgb(0, 102, 204),
        "noclass" => Color.FromArgb(204, 136, 0),
        "meeting" => Color.FromArgb(0, 119, 68),
        _ => Color.FromArgb(68, 68, 102)
    };

    private static string NormalizeEventType(string type) => type.Equals("NoClass", StringComparison.OrdinalIgnoreCase)
        ? "No Class" : type;

    private void ShowMessage(string text, bool error)
    {
        message.Text = text;
        message.ForeColor = error ? AccentColor : Color.LightGreen;
    }

    private SqlConnection OpenConnection()
    {
        var connection = new SqlConnection(DatabaseConnection.ConnectionString);
        try { DatabaseConnection.Open(connection); return connection; }
        catch { connection.Dispose(); throw; }
    }

    private sealed record CourseChoice(int? Id, string Name)
    {
        public override string ToString() => Name;
    }
}
}
