using System.Data;
using System.Data.SqlClient;

namespace SMART;

public sealed class CalendarControl : UserControl
{
    private static readonly Color BgColor = Color.FromArgb(13, 17, 38);
    private static readonly Color CardColor = Color.FromArgb(22, 33, 62);
    private static readonly Color AccentColor = Color.FromArgb(233, 69, 96);
    private static readonly Color TextGray = Color.FromArgb(150, 150, 170);
    private static readonly Color DimGray = Color.FromArgb(85, 85, 119);
    private readonly string employeeId;
    private readonly string instructorName;
    private readonly List<(int Id, string Title)> courses;
    private DateTime displayedMonth = new(DateTime.Today.Year, DateTime.Today.Month, 1);
    private readonly TableLayoutPanel calendarGrid = new();
    private readonly Label monthLabel = new();
    private readonly RoundedTextBox titleInput = new();
    private readonly RoundedTextBox descriptionInput = new();
    private readonly DateTimePicker eventDate = new();
    private readonly ComboBox eventType = new();
    private readonly ComboBox coursePicker = new();
    private readonly CustomButton deleteButton = new();
    private readonly Label message = new();
    private Dictionary<DateTime, List<CalendarEvent>> eventsByDate = new();
    private int? selectedEventId;

    private sealed record CalendarEvent(int Id, string Title, DateTime Date, string Type,
        int? CourseId, bool AutoGenerated, string? Description, string? OwnerEmployeeId);

    public CalendarControl(string employeeId, string instructorName, List<(int Id, string Title)> courses)
    {
        this.employeeId = employeeId;
        this.instructorName = instructorName;
        this.courses = courses;
        BackColor = BgColor;
        Font = new Font("Segoe UI", 9F);
        AccessibleDescription = "Academic calendar for " + instructorName;
        BuildLayout();
        Load += (_, _) => LoadEvents();
    }

    private void BuildLayout()
    {
        var root = new TableLayoutPanel
        {
            Dock = DockStyle.Fill, BackColor = BgColor, ColumnCount = 1, RowCount = 4,
            Padding = new Padding(4)
        };
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 44));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 62));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 34));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));

        var header = new Panel { Dock = DockStyle.Fill, BackColor = BgColor };
        var heading = new Label
        {
            Text = "📅 Calendar", Dock = DockStyle.Left, Width = 220,
            ForeColor = Color.White, Font = new Font("Segoe UI", 20F, FontStyle.Bold),
            TextAlign = ContentAlignment.MiddleLeft
        };
        var previous = MakeButton("← Prev", CardColor, 82, 34);
        previous.Dock = DockStyle.Right;
        previous.Click += (_, _) => { displayedMonth = displayedMonth.AddMonths(-1); LoadEvents(); };
        var next = MakeButton("Next →", CardColor, 82, 34);
        next.Dock = DockStyle.Right;
        next.Click += (_, _) => { displayedMonth = displayedMonth.AddMonths(1); LoadEvents(); };
        monthLabel.Dock = DockStyle.Right;
        monthLabel.Width = 175;
        monthLabel.ForeColor = Color.White;
        monthLabel.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        monthLabel.TextAlign = ContentAlignment.MiddleCenter;
        header.Controls.Add(previous);
        header.Controls.Add(next);
        header.Controls.Add(monthLabel);
        header.Controls.Add(heading);

        calendarGrid.Dock = DockStyle.Fill;
        calendarGrid.BackColor = BgColor;
        calendarGrid.ColumnCount = 7;
        calendarGrid.RowCount = 7;
        calendarGrid.Margin = new Padding(0);
        for (int col = 0; col < 7; col++) calendarGrid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F / 7));
        calendarGrid.RowStyles.Add(new RowStyle(SizeType.Absolute, 25));
        for (int row = 1; row < 7; row++) calendarGrid.RowStyles.Add(new RowStyle(SizeType.Percent, 100F / 6));
        string[] weekdays = { "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat" };
        for (int col = 0; col < weekdays.Length; col++)
        {
            calendarGrid.Controls.Add(new Label
            {
                Text = weekdays[col], Dock = DockStyle.Fill, TextAlign = ContentAlignment.MiddleCenter,
                ForeColor = TextGray, Font = new Font("Segoe UI", 9F, FontStyle.Bold),
                BackColor = CardColor, Margin = new Padding(1)
            }, col, 0);
        }

        var form = BuildEventForm();
        root.Controls.Add(header, 0, 0);
        root.Controls.Add(calendarGrid, 0, 1);
        root.Controls.Add(form, 0, 2);
        root.Controls.Add(BuildLegend(), 0, 3);
        Controls.Add(root);
    }

    private Control BuildEventForm()
    {
        var card = new CustomPanel
        {
            Dock = DockStyle.Fill, BackColor = CardColor, BorderColor = CardColor,
            BorderWidth = 0, CornerRadius = 8, Padding = new Padding(10)
        };
        var rows = new TableLayoutPanel
        {
            Dock = DockStyle.Fill, BackColor = CardColor, ColumnCount = 1, RowCount = 3,
            Padding = Padding.Empty
        };
        rows.RowStyles.Add(new RowStyle(SizeType.Percent, 35));
        rows.RowStyles.Add(new RowStyle(SizeType.Percent, 35));
        rows.RowStyles.Add(new RowStyle(SizeType.Percent, 30));

        StyleInput(titleInput, "Event title");
        titleInput.Dock = DockStyle.Fill;
        titleInput.Margin = new Padding(4);
        eventDate.Format = DateTimePickerFormat.Short;
        StyleDate(eventDate);
        eventDate.Dock = DockStyle.Fill;
        eventDate.Margin = new Padding(4);
        eventType.DropDownStyle = ComboBoxStyle.DropDownList;
        eventType.Items.AddRange(new object[] { "Quiz", "Exam", "No Class", "Meeting", "Holiday", "Other" });
        eventType.SelectedIndex = 5;
        StyleCombo(eventType);
        eventType.Dock = DockStyle.Fill;
        eventType.Margin = new Padding(4);
        var first = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 6, BackColor = CardColor };
        first.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 48));
        first.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42));
        first.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 42));
        first.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 24));
        first.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 40));
        first.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 34));
        first.Controls.Add(MakeFieldLabel("Title"), 0, 0);
        first.Controls.Add(titleInput, 1, 0);
        first.Controls.Add(MakeFieldLabel("Date"), 2, 0);
        first.Controls.Add(eventDate, 3, 0);
        first.Controls.Add(MakeFieldLabel("Type"), 4, 0);
        first.Controls.Add(eventType, 5, 0);

        StyleInput(descriptionInput, "Optional event details");
        descriptionInput.Dock = DockStyle.Fill;
        descriptionInput.Margin = new Padding(4);
        coursePicker.DropDownStyle = ComboBoxStyle.DropDownList;
        coursePicker.Items.Add(new CourseChoice(null, "None"));
        foreach (var course in courses) coursePicker.Items.Add(new CourseChoice(course.Id, course.Title));
        coursePicker.SelectedIndex = 0;
        StyleCombo(coursePicker);
        coursePicker.Dock = DockStyle.Fill;
        coursePicker.Margin = new Padding(4);
        var second = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 4, BackColor = CardColor };
        second.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 92));
        second.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58));
        second.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 118));
        second.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42));
        second.Controls.Add(MakeFieldLabel("Description"), 0, 0);
        second.Controls.Add(descriptionInput, 1, 0);
        second.Controls.Add(MakeFieldLabel("Course (optional)"), 2, 0);
        second.Controls.Add(coursePicker, 3, 0);

        var actions = new FlowLayoutPanel { Dock = DockStyle.Fill, BackColor = CardColor, WrapContents = false };
        var add = MakeButton("ADD EVENT", AccentColor, 130, 34);
        add.Click += (_, _) => AddEvent();
        deleteButton.Text = "DELETE SELECTED";
        deleteButton.BackColor = Color.FromArgb(80, 30, 40);
        deleteButton.ForeColor = AccentColor;
        deleteButton.Size = new Size(150, 34);
        deleteButton.BorderRadius = 6;
        deleteButton.BorderSize = 0;
        deleteButton.Enabled = false;
        deleteButton.Click += (_, _) => DeleteSelectedEvent();
        message.AutoSize = false;
        message.Width = 350;
        message.Height = 34;
        message.ForeColor = TextGray;
        message.TextAlign = ContentAlignment.MiddleLeft;
        actions.Controls.Add(add);
        actions.Controls.Add(deleteButton);
        actions.Controls.Add(message);

        rows.Controls.Add(first, 0, 0);
        rows.Controls.Add(second, 0, 1);
        rows.Controls.Add(actions, 0, 2);
        card.Controls.Add(rows);
        return card;
    }

    private Control BuildLegend()
    {
        var legend = new FlowLayoutPanel
        {
            Dock = DockStyle.Fill, BackColor = BgColor, WrapContents = false,
            FlowDirection = FlowDirection.LeftToRight, Padding = new Padding(2, 4, 0, 0)
        };
        AddLegend(legend, "Holiday", "Holiday");
        AddLegend(legend, "Exam", "Exam");
        AddLegend(legend, "Quiz", "Quiz");
        AddLegend(legend, "No Class", "No Class");
        AddLegend(legend, "Meeting", "Meeting");
        AddLegend(legend, "Event", "Event");
        AddLegend(legend, "Other", "Other");
        return legend;
    }

    private static void AddLegend(FlowLayoutPanel legend, string type, string label)
    {
        var item = new FlowLayoutPanel { AutoSize = true, WrapContents = false, Margin = new Padding(3, 0, 9, 0) };
        item.Controls.Add(new Panel { Width = 10, Height = 10, BackColor = ColorForEventType(type), Margin = new Padding(0, 4, 4, 0) });
        item.Controls.Add(new Label { Text = label, AutoSize = true, ForeColor = TextGray, Font = new Font("Segoe UI", 8F) });
        legend.Controls.Add(item);
    }

    private void LoadEvents()
    {
        monthLabel.Text = displayedMonth.ToString("MMMM yyyy");
        try
        {
            eventsByDate = new Dictionary<DateTime, List<CalendarEvent>>();
            using var connection = OpenConnection();
            using var command = new SqlCommand(@"SELECT EventId, Title, EventDate, EventType,
                    CourseId, IsAutoGenerated, Description, InstructorEmployeeID
                FROM dbo.Events
                WHERE (InstructorEmployeeID = @empId OR InstructorEmployeeID IS NULL)
                    AND YEAR(EventDate) = @year AND MONTH(EventDate) = @month
                ORDER BY EventDate, Title", connection);
            command.Parameters.Add("@empId", SqlDbType.NVarChar, 50).Value = employeeId;
            command.Parameters.Add("@year", SqlDbType.Int).Value = displayedMonth.Year;
            command.Parameters.Add("@month", SqlDbType.Int).Value = displayedMonth.Month;
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                var item = new CalendarEvent(reader.GetInt32(0), reader.GetString(1), reader.GetDateTime(2),
                    reader.GetString(3), reader.IsDBNull(4) ? null : reader.GetInt32(4),
                    reader.GetBoolean(5), reader.IsDBNull(6) ? null : reader.GetString(6),
                    reader.IsDBNull(7) ? null : reader.GetString(7));
                if (!eventsByDate.TryGetValue(item.Date.Date, out var dayEvents))
                    eventsByDate[item.Date.Date] = dayEvents = new List<CalendarEvent>();
                dayEvents.Add(item);
            }
            message.Text = "";
        }
        catch (SqlException ex)
        {
            eventsByDate.Clear();
            message.Text = "Calendar could not load: " + ex.Message;
            message.ForeColor = AccentColor;
        }
        DrawCalendar();
    }

    private void DrawCalendar()
    {
        while (calendarGrid.Controls.Count > 7)
        {
            var control = calendarGrid.Controls[7];
            calendarGrid.Controls.RemoveAt(7);
            control.Dispose();
        }
        DateTime firstDay = displayedMonth;
        DateTime start = firstDay.AddDays(-(int)firstDay.DayOfWeek);
        DateTime today = DateTime.Today;
        for (int i = 0; i < 42; i++)
        {
            DateTime date = start.AddDays(i);
            int column = i % 7;
            int row = (i / 7) + 1;
            Color cellBack = column == 0 || column == 6 ? Color.FromArgb(18, 23, 45) : CardColor;
            var cell = new CustomPanel
            {
                Dock = DockStyle.Fill, Margin = new Padding(1), Padding = new Padding(3),
                BackColor = date.Date == today ? Color.FromArgb(60, 30, 50) : cellBack,
                BorderColor = date.Date == today ? AccentColor : Color.FromArgb(35, 43, 69),
                BorderWidth = date.Date == today ? 2 : 1, CornerRadius = 4, Cursor = Cursors.Hand,
                Tag = date
            };
            cell.Click += DayCell_Click;
            var dayNumber = new Label
            {
                Text = date.Day.ToString(), AutoSize = false, Dock = DockStyle.Top, Height = 17,
                ForeColor = date.Month == displayedMonth.Month ? Color.White : DimGray,
                Font = new Font("Segoe UI", 10F, FontStyle.Bold), BackColor = Color.Transparent,
                Cursor = Cursors.Hand, Tag = date
            };
            dayNumber.Click += DayCell_Click;
            if (eventsByDate.TryGetValue(date.Date, out var dayEvents))
            {
                var eventList = new FlowLayoutPanel
                {
                    Dock = DockStyle.Fill, FlowDirection = FlowDirection.TopDown,
                    WrapContents = false, AutoScroll = false, BackColor = Color.Transparent,
                    Margin = Padding.Empty, Padding = Padding.Empty
                };
                foreach (var ev in dayEvents.Take(2))
                {
                    var chip = MakeButton(ev.Title, ColorForEventType(ev.Type), Math.Max(35, calendarGrid.ClientSize.Width / 7 - 12), 16);
                    chip.Font = new Font("Segoe UI", 7F);
                    chip.TextAlign = ContentAlignment.MiddleLeft;
                    chip.Tag = ev;
                    chip.Margin = new Padding(0, 1, 0, 1);
                    chip.Click += EventChip_Click;
                    eventList.Controls.Add(chip);
                }
                if (dayEvents.Count > 2)
                {
                    var more = new Label
                    {
                        Text = $"+{dayEvents.Count - 2} more", AutoSize = false, Height = 15,
                        ForeColor = TextGray, Font = new Font("Segoe UI", 7F), Cursor = Cursors.Hand,
                        Tag = date
                    };
                    more.Click += DayCell_Click;
                    eventList.Controls.Add(more);
                }
                cell.Controls.Add(eventList);
            }
            cell.Controls.Add(dayNumber);
            calendarGrid.Controls.Add(cell, column, row);
        }
    }

    private void DayCell_Click(object? sender, EventArgs e)
    {
        DateTime date = sender switch
        {
            Control { Tag: DateTime taggedDate } => taggedDate,
            Control { Parent: Control { Tag: DateTime parentDate } } => parentDate,
            _ => eventDate.Value.Date
        };
        eventDate.Value = date;
        if (date.Month != displayedMonth.Month || date.Year != displayedMonth.Year)
        {
            displayedMonth = new DateTime(date.Year, date.Month, 1);
            LoadEvents();
        }
        selectedEventId = null;
        deleteButton.Enabled = false;
        message.Text = eventsByDate.TryGetValue(date.Date, out var dayEvents)
            ? string.Join(" · ", dayEvents.Select(item => item.Title)) : "Selected " + date.ToString("MMM d");
        message.ForeColor = TextGray;
    }

    private void EventChip_Click(object? sender, EventArgs e)
    {
        if (sender is not Control { Tag: CalendarEvent ev }) return;
        eventDate.Value = ev.Date;
        titleInput.Text = ev.Title;
        descriptionInput.Text = ev.Description ?? "";
        eventType.SelectedItem = NormalizeEventType(ev.Type);
        selectedEventId = ev.Id;
        deleteButton.Enabled = !ev.AutoGenerated && ev.Type != "Holiday" && IsOwnedByInstructor(ev.Id);
        message.Text = deleteButton.Enabled ? "Selected event." : "Auto-generated events cannot be deleted.";
        message.ForeColor = TextGray;
    }

    private bool IsOwnedByInstructor(int eventId)
    {
        var ev = eventsByDate.Values.SelectMany(value => value).FirstOrDefault(item => item.Id == eventId);
        return ev != null && !ev.AutoGenerated &&
            string.Equals(ev.OwnerEmployeeId, employeeId, StringComparison.OrdinalIgnoreCase);
    }

    private void AddEvent()
    {
        string title = titleInput.Text.Trim();
        string description = descriptionInput.Text.Trim();
        if (title.Length == 0 || title.Length > 200)
        {
            ShowMessage("Enter a title of 1 to 200 characters.", true);
            return;
        }
        if (description.Length > 500)
        {
            ShowMessage("Description must be 500 characters or fewer.", true);
            return;
        }
        try
        {
            using var connection = OpenConnection();
            using var command = new SqlCommand(@"INSERT INTO dbo.Events
                    (Title, Description, EventDate, EventType, CourseId, InstructorEmployeeID, IsAutoGenerated)
                VALUES (@title, @desc, @date, @type, @courseId, @empId, 0)", connection);
            command.Parameters.Add("@title", SqlDbType.NVarChar, 200).Value = title;
            command.Parameters.Add("@desc", SqlDbType.NVarChar, 500).Value = string.IsNullOrWhiteSpace(description) ? DBNull.Value : description;
            command.Parameters.Add("@date", SqlDbType.Date).Value = eventDate.Value.Date;
            command.Parameters.Add("@type", SqlDbType.NVarChar, 50).Value = eventType.SelectedItem?.ToString() ?? "Other";
            int? courseId = (coursePicker.SelectedItem as CourseChoice)?.Id;
            command.Parameters.Add("@courseId", SqlDbType.Int).Value = courseId.HasValue ? courseId.Value : DBNull.Value;
            command.Parameters.Add("@empId", SqlDbType.NVarChar, 50).Value = employeeId;
            command.ExecuteNonQuery();
            titleInput.Text = "";
            descriptionInput.Text = "";
            selectedEventId = null;
            deleteButton.Enabled = false;
            if (eventDate.Value.Month != displayedMonth.Month || eventDate.Value.Year != displayedMonth.Year)
                displayedMonth = new DateTime(eventDate.Value.Year, eventDate.Value.Month, 1);
            LoadEvents();
            ShowMessage("Event added.", false);
        }
        catch (SqlException ex) { ShowMessage("Could not add event: " + ex.Message, true); }
    }

    private void DeleteSelectedEvent()
    {
        if (!selectedEventId.HasValue) return;
        try
        {
            using var connection = OpenConnection();
            using var command = new SqlCommand(@"DELETE FROM dbo.Events
                WHERE EventId = @id AND IsAutoGenerated = 0 AND InstructorEmployeeID = @empId", connection);
            command.Parameters.Add("@id", SqlDbType.Int).Value = selectedEventId.Value;
            command.Parameters.Add("@empId", SqlDbType.NVarChar, 50).Value = employeeId;
            if (command.ExecuteNonQuery() == 0)
            {
                ShowMessage("Only your own manual events can be deleted.", true);
                return;
            }
            selectedEventId = null;
            deleteButton.Enabled = false;
            LoadEvents();
            ShowMessage("Event deleted.", false);
        }
        catch (SqlException ex) { ShowMessage("Could not delete event: " + ex.Message, true); }
    }

    private static Color ColorForEventType(string? type) => type?.Replace(" ", "", StringComparison.Ordinal).ToLowerInvariant() switch
    {
        "holiday" => Color.FromArgb(204, 34, 68),
        "exam" => Color.FromArgb(106, 13, 173),
        "quiz" => Color.FromArgb(0, 102, 204),
        "noclass" => Color.FromArgb(204, 136, 0),
        "meeting" => Color.FromArgb(0, 119, 68),
        _ => Color.FromArgb(68, 68, 102)
    };

    private static string NormalizeEventType(string type) => type.Equals("NoClass", StringComparison.OrdinalIgnoreCase)
        ? "No Class" : type;

    private void ShowMessage(string text, bool error)
    {
        message.Text = text;
        message.ForeColor = error ? AccentColor : Color.LightGreen;
    }

    private SqlConnection OpenConnection()
    {
        var connection = new SqlConnection(DatabaseConnection.ConnectionString);
        try { DatabaseConnection.Open(connection); return connection; }
        catch { connection.Dispose(); throw; }
    }

    private static CustomButton MakeButton(string text, Color color, int width, int height) => new()
    {
        Text = text, BackColor = color, ForeColor = Color.White,
        Size = new Size(width, height), BorderRadius = 6, BorderSize = 0,
        Cursor = Cursors.Hand, Font = new Font("Segoe UI", 9F, FontStyle.Bold)
    };

    private static void StyleInput(RoundedTextBox input, string placeholder)
    {
        input.FillColor = BgColor;
        input.BorderColor = AccentColor;
        input.FocusBorderColor = AccentColor;
        input.BorderRadius = 6;
        input.Font = new Font("Segoe UI", 9F);
        input.ForeColor = Color.White;
        input.PlaceholderText = placeholder;
    }

    private static void StyleDate(DateTimePicker picker)
    {
        picker.CalendarMonthBackground = CardColor;
        picker.CalendarForeColor = Color.White;
        picker.CalendarTitleBackColor = AccentColor;
        picker.CalendarTitleForeColor = Color.White;
        picker.BackColor = CardColor;
        picker.ForeColor = Color.White;
        picker.Font = new Font("Segoe UI", 9F);
        picker.Format = DateTimePickerFormat.Short;
    }

    private static void StyleCombo(ComboBox combo)
    {
        combo.BackColor = BgColor;
        combo.ForeColor = Color.White;
        combo.Font = new Font("Segoe UI", 9F);
    }

    private static Label MakeFieldLabel(string text) => new()
    {
        Text = text, Dock = DockStyle.Fill, ForeColor = TextGray,
        TextAlign = ContentAlignment.MiddleLeft, Font = new Font("Segoe UI", 8F)
    };

    private sealed record CourseChoice(int? Id, string Name)
    {
        public override string ToString() => Name;
    }
}
