#nullable disable
namespace SMART
{
    public sealed partial class InboxControl
    {
        private System.ComponentModel.IContainer components;
        private Panel pnlInboxAdmin;
        private Label subtitle;
        private TableLayoutPanel root;
        private Label heading;
        private SplitContainer split;
        private CustomPanel filterPanel;
        private Label unreadCountLabel;
        private ComboBox filterPicker;
        private CheckBox unreadOnly;
        private FlowLayoutPanel filterRow;
        private CustomButton refreshButton;
        private FlowLayoutPanel messageList;
        private CustomPanel detail;
        private TableLayoutPanel detailLayout;
        private Label fromLabel;
        private Label subjectLabel;
        private Label sentLabel;
        private Panel separator;
        private RichTextBox bodyView;
        private RichTextBox replyInput;
        private Label replyLabel;
        private FlowLayoutPanel actions;
        private CustomButton replyButton;
        private CustomButton resolveButton;
        private Label statusLabel;
        private CustomPanel messageCardTemplate;
        private Label messageInstructorTemplate;
        private Label messageSubjectTemplate;
        private Label messageSentTemplate;
        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            pnlInboxAdmin = new Panel();
            subtitle = new Label();
            root = new TableLayoutPanel();
            heading = new Label();
            split = new SplitContainer();
            filterPanel = new CustomPanel();
            unreadCountLabel = new Label();
            filterPicker = new ComboBox();
            unreadOnly = new CheckBox();
            filterRow = new FlowLayoutPanel();
            refreshButton = new CustomButton();
            messageList = new FlowLayoutPanel();
            detail = new CustomPanel();
            detailLayout = new TableLayoutPanel();
            fromLabel = new Label();
            subjectLabel = new Label();
            sentLabel = new Label();
            separator = new Panel();
            bodyView = new RichTextBox();
            replyInput = new RichTextBox();
            replyLabel = new Label();
            actions = new FlowLayoutPanel();
            replyButton = new CustomButton();
            resolveButton = new CustomButton();
            statusLabel = new Label();
            messageCardTemplate = new CustomPanel();
            messageInstructorTemplate = new Label();
            messageSubjectTemplate = new Label();
            messageSentTemplate = new Label();
            ((System.ComponentModel.ISupportInitialize)split).BeginInit();
            split.Panel1.SuspendLayout();
            split.Panel2.SuspendLayout();
            split.SuspendLayout();
            root.SuspendLayout();
            pnlInboxAdmin.SuspendLayout();
            filterPanel.SuspendLayout();
            filterRow.SuspendLayout();
            messageList.SuspendLayout();
            detail.SuspendLayout();
            detailLayout.SuspendLayout();
            actions.SuspendLayout();
            messageCardTemplate.SuspendLayout();
            SuspendLayout();
            root.Name = "root";
            root.Dock = DockStyle.Fill;
            root.ColumnCount = 1;
            root.RowCount = 1;
            root.BackColor = Color.Transparent;
            root.Padding = new Padding(4);
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            heading.Name = "heading";
            heading.Text = "Instructor Inbox";
            heading.BackColor = Color.Transparent;
            heading.AutoSize = false;
            heading.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            heading.Location = new Point(25, 22);
            heading.Size = new Size(1150, 46);
            heading.ForeColor = Color.White;
            heading.TextAlign = ContentAlignment.MiddleLeft;
            heading.Font = new Font("Gadugi", 20F, FontStyle.Bold);
            subtitle.Name = "subtitle";
            subtitle.Text = "View instructor messages, send replies, and resolve requests";
            subtitle.BackColor = Color.Transparent;
            subtitle.ForeColor = Color.White;
            subtitle.Font = new Font("Bahnschrift Light", 10F);
            subtitle.AutoSize = false;
            subtitle.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            subtitle.Location = new Point(29, 76);
            subtitle.Size = new Size(1146, 26);
            subtitle.TextAlign = ContentAlignment.MiddleLeft;
            pnlInboxAdmin.Name = "pnlInboxAdmin";
            pnlInboxAdmin.BackColor = Color.Transparent;
            pnlInboxAdmin.Dock = DockStyle.Top;
            pnlInboxAdmin.Location = new Point(0, 0);
            pnlInboxAdmin.Size = new Size(1200, 106);
            pnlInboxAdmin.Controls.Add(subtitle);
            pnlInboxAdmin.Controls.Add(heading);
            split.Name = "split";
            split.BackColor = Color.Transparent;
            split.Size = new Size(1192, 664);
            split.Dock = DockStyle.Fill;
            split.Orientation = Orientation.Vertical;
            split.SplitterWidth = 8;
            split.SplitterDistance = 390;
            split.FixedPanel = FixedPanel.Panel1;
            split.Panel1MinSize = 280;
            split.Panel2MinSize = 400;
            split.BorderStyle = BorderStyle.None;
            split.Panel1.BackColor = Color.Transparent;
            split.Panel2.BackColor = Color.Transparent;
            filterPanel.Name = "filterPanel";
            filterPanel.Dock = DockStyle.Top;
            filterPanel.Height = 86;
            filterPanel.BackColor = Color.FromArgb(178, 22, 33, 62);
            filterPanel.BorderColor = Color.FromArgb(22, 33, 62);
            filterPanel.BorderWidth = 0;
            filterPanel.CornerRadius = 7;
            filterPanel.Padding = new Padding(9);
            unreadCountLabel.Name = "unreadCountLabel";
            unreadCountLabel.BackColor = Color.Transparent;
            unreadCountLabel.Text = "📬 0 unread messages";
            unreadCountLabel.Dock = DockStyle.Top;
            unreadCountLabel.ForeColor = Color.FromArgb(233, 69, 96);
            unreadCountLabel.TextAlign = ContentAlignment.MiddleLeft;
            unreadCountLabel.Height = 25;
            unreadCountLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            filterPicker.Name = "filterPicker";
            filterPicker.DropDownStyle = ComboBoxStyle.DropDownList;
            filterPicker.Width = 120;
            filterPicker.BackColor = Color.FromArgb(13, 17, 38);
            filterPicker.ForeColor = Color.White;
            filterPicker.Items.AddRange(new object[] { "All", "Pending", "Resolved" });
            unreadOnly.Name = "unreadOnly";
            unreadOnly.Text = "Unread only";
            unreadOnly.ForeColor = Color.FromArgb(150, 150, 170);
            unreadOnly.BackColor = Color.Transparent;
            unreadOnly.AutoSize = true;
            filterRow.Name = "filterRow";
            filterRow.Dock = DockStyle.Fill;
            filterRow.WrapContents = false;
            filterRow.BackColor = Color.Transparent;
            filterRow.Padding = new Padding(0, 3, 0, 0);
            refreshButton.Name = "refreshButton";
            refreshButton.Text = "Refresh";
            refreshButton.BackColor = Color.FromArgb(55, 62, 86);
            refreshButton.ForeColor = Color.White;
            refreshButton.Size = new Size(75, 28);
            refreshButton.BorderRadius = 6;
            refreshButton.BorderSize = 0;
            refreshButton.Cursor = Cursors.Hand;
            refreshButton.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            filterRow.Controls.Add(filterPicker);
            filterRow.Controls.Add(unreadOnly);
            filterRow.Controls.Add(refreshButton);
            filterPanel.Controls.Add(filterRow);
            filterPanel.Controls.Add(unreadCountLabel);
            messageList.Name = "messageList";
            messageList.Dock = DockStyle.Fill;
            messageList.FlowDirection = FlowDirection.TopDown;
            messageList.WrapContents = false;
            messageList.AutoScroll = true;
            messageList.BackColor = Color.Transparent;
            split.Panel1.Controls.Add(messageList);
            split.Panel1.Controls.Add(filterPanel);
            detail.Name = "detail";
            detail.Dock = DockStyle.Fill;
            detail.BackColor = Color.FromArgb(178, 22, 33, 62);
            detail.BorderColor = Color.FromArgb(22, 33, 62);
            detail.BorderWidth = 0;
            detail.CornerRadius = 8;
            detail.Padding = new Padding(16);
            detailLayout.Name = "detailLayout";
            detailLayout.Dock = DockStyle.Fill;
            detailLayout.ColumnCount = 1;
            detailLayout.RowCount = 9;
            detailLayout.BackColor = Color.Transparent;
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 1));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 42));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 25));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 30));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44));
            detailLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            fromLabel.Name = "fromLabel";
            fromLabel.BackColor = Color.Transparent;
            fromLabel.Text = "From: Instructor name";
            fromLabel.Dock = DockStyle.Fill;
            fromLabel.ForeColor = Color.White;
            fromLabel.TextAlign = ContentAlignment.MiddleLeft;
            fromLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            fromLabel.AutoEllipsis = true;
            subjectLabel.Name = "subjectLabel";
            subjectLabel.BackColor = Color.Transparent;
            subjectLabel.Text = "Subject: Message subject";
            subjectLabel.Dock = DockStyle.Fill;
            subjectLabel.ForeColor = Color.White;
            subjectLabel.TextAlign = ContentAlignment.MiddleLeft;
            subjectLabel.Font = new Font("Segoe UI", 10F);
            subjectLabel.AutoEllipsis = true;
            sentLabel.Name = "sentLabel";
            sentLabel.BackColor = Color.Transparent;
            sentLabel.Text = "Sent: Message date";
            sentLabel.Dock = DockStyle.Fill;
            sentLabel.ForeColor = Color.FromArgb(150, 150, 170);
            sentLabel.TextAlign = ContentAlignment.MiddleLeft;
            sentLabel.Font = new Font("Segoe UI", 10F);
            sentLabel.AutoEllipsis = true;
            separator.Name = "separator";
            separator.Dock = DockStyle.Fill;
            separator.BackColor = Color.FromArgb(50, 60, 82);
            separator.Height = 1;
            bodyView.Name = "bodyView";
            bodyView.Dock = DockStyle.Fill;
            bodyView.BackColor = Color.FromArgb(26, 26, 46);
            bodyView.ForeColor = Color.White;
            bodyView.Font = new Font("Segoe UI", 10F);
            bodyView.BorderStyle = BorderStyle.None;
            bodyView.ReadOnly = true;
            bodyView.ScrollBars = RichTextBoxScrollBars.Vertical;
            replyInput.Name = "replyInput";
            replyInput.Dock = DockStyle.Fill;
            replyInput.BackColor = Color.FromArgb(26, 26, 46);
            replyInput.ForeColor = Color.White;
            replyInput.Font = new Font("Segoe UI", 10F);
            replyInput.BorderStyle = BorderStyle.None;
            replyInput.ReadOnly = false;
            replyInput.ScrollBars = RichTextBoxScrollBars.Vertical;
            replyLabel.Name = "replyLabel";
            replyLabel.BackColor = Color.Transparent;
            replyLabel.Text = "Admin Reply";
            replyLabel.Dock = DockStyle.Fill;
            replyLabel.ForeColor = Color.FromArgb(150, 150, 170);
            replyLabel.TextAlign = ContentAlignment.MiddleLeft;
            actions.Name = "actions";
            actions.Dock = DockStyle.Fill;
            actions.BackColor = Color.Transparent;
            actions.WrapContents = false;
            replyButton.Name = "replyButton";
            replyButton.Text = "📤 SEND REPLY";
            replyButton.BackColor = Color.FromArgb(0, 140, 200);
            replyButton.ForeColor = Color.White;
            replyButton.Size = new Size(140, 36);
            replyButton.BorderRadius = 6;
            replyButton.BorderSize = 0;
            replyButton.Cursor = Cursors.Hand;
            replyButton.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            resolveButton.Name = "resolveButton";
            resolveButton.Text = "✅ MARK RESOLVED";
            resolveButton.BackColor = Color.FromArgb(0, 120, 50);
            resolveButton.ForeColor = Color.White;
            resolveButton.Size = new Size(160, 36);
            resolveButton.BorderRadius = 6;
            resolveButton.BorderSize = 0;
            resolveButton.Cursor = Cursors.Hand;
            resolveButton.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
            actions.Controls.Add(replyButton);
            actions.Controls.Add(resolveButton);
            statusLabel.Name = "statusLabel";
            statusLabel.BackColor = Color.Transparent;
            statusLabel.Text = "";
            statusLabel.Dock = DockStyle.Fill;
            statusLabel.ForeColor = Color.FromArgb(150, 150, 170);
            statusLabel.TextAlign = ContentAlignment.MiddleLeft;
            detailLayout.Controls.Add(fromLabel, 0, 0);
            detailLayout.Controls.Add(subjectLabel, 0, 1);
            detailLayout.Controls.Add(sentLabel, 0, 2);
            detailLayout.Controls.Add(separator, 0, 3);
            detailLayout.Controls.Add(bodyView, 0, 4);
            detailLayout.Controls.Add(replyLabel, 0, 5);
            detailLayout.Controls.Add(replyInput, 0, 6);
            detailLayout.Controls.Add(actions, 0, 7);
            detailLayout.Controls.Add(statusLabel, 0, 8);
            detail.Controls.Add(detailLayout);
            split.Panel2.Controls.Add(detail);
            root.Controls.Add(split, 0, 0);
            messageCardTemplate.Name = "messageCardTemplate";
            messageCardTemplate.Size = new Size(368, 75);
            messageCardTemplate.BackColor = Color.FromArgb(178, 22, 33, 62);
            messageCardTemplate.BorderColor = Color.FromArgb(75, 85, 105);
            messageCardTemplate.BorderWidth = 2;
            messageCardTemplate.CornerRadius = 6;
            messageCardTemplate.Margin = new Padding(3, 4, 3, 3);
            messageCardTemplate.Padding = new Padding(9, 3, 4, 2);
            messageCardTemplate.Cursor = Cursors.Hand;
            messageInstructorTemplate.Name = "messageInstructorTemplate";
            messageInstructorTemplate.BackColor = Color.Transparent;
            messageInstructorTemplate.Text = "Instructor name";
            messageInstructorTemplate.Dock = DockStyle.Top;
            messageInstructorTemplate.ForeColor = Color.White;
            messageInstructorTemplate.TextAlign = ContentAlignment.MiddleLeft;
            messageInstructorTemplate.Height = 20;
            messageInstructorTemplate.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            messageInstructorTemplate.AutoEllipsis = true;
            messageSubjectTemplate.Name = "messageSubjectTemplate";
            messageSubjectTemplate.BackColor = Color.Transparent;
            messageSubjectTemplate.Text = "Message subject";
            messageSubjectTemplate.Dock = DockStyle.Top;
            messageSubjectTemplate.ForeColor = Color.FromArgb(150, 150, 170);
            messageSubjectTemplate.TextAlign = ContentAlignment.MiddleLeft;
            messageSubjectTemplate.Height = 20;
            messageSubjectTemplate.Font = new Font("Segoe UI", 8F);
            messageSubjectTemplate.AutoEllipsis = true;
            messageSentTemplate.Name = "messageSentTemplate";
            messageSentTemplate.BackColor = Color.Transparent;
            messageSentTemplate.Text = "Message date";
            messageSentTemplate.Dock = DockStyle.Fill;
            messageSentTemplate.ForeColor = Color.FromArgb(150, 150, 170);
            messageSentTemplate.TextAlign = ContentAlignment.MiddleLeft;
            messageSentTemplate.Font = new Font("Segoe UI", 7F);
            messageCardTemplate.Controls.Add(messageSentTemplate);
            messageCardTemplate.Controls.Add(messageSubjectTemplate);
            messageCardTemplate.Controls.Add(messageInstructorTemplate);
            messageList.Controls.Add(messageCardTemplate);
            Load += InboxControl_Load;
            filterPicker.SelectedIndexChanged += FilterChanged;
            unreadOnly.CheckedChanged += FilterChanged;
            refreshButton.Click += RefreshButton_Click;
            replyButton.Click += ReplyButton_Click;
            resolveButton.Click += ResolveButton_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.Transparent;
            Font = new Font("Segoe UI", 9F);
            Name = "InboxControl";
            Size = new Size(1200, 720);
            Controls.Add(root);
            Controls.Add(pnlInboxAdmin);
            root.ResumeLayout(false);
            pnlInboxAdmin.ResumeLayout(false);
            root.PerformLayout();
            filterPanel.ResumeLayout(false);
            filterPanel.PerformLayout();
            filterRow.ResumeLayout(false);
            filterRow.PerformLayout();
            messageList.ResumeLayout(false);
            messageList.PerformLayout();
            detail.ResumeLayout(false);
            detail.PerformLayout();
            detailLayout.ResumeLayout(false);
            detailLayout.PerformLayout();
            actions.ResumeLayout(false);
            actions.PerformLayout();
            messageCardTemplate.ResumeLayout(false);
            messageCardTemplate.PerformLayout();
            split.Panel1.ResumeLayout(false);
            split.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)split).EndInit();
            split.ResumeLayout(false);
            ResumeLayout(false);
        }
    }
}
