using System.Drawing;
using System.Windows.Forms;
namespace SMART
{
    partial class InstructorUI
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InstructorUI));
            flpScheduleInstructor = new RoundedFlowLayoutPanel();
            picScheduleInstructor = new PictureBox();
            lblScheduleInstructor = new Label();
            flpAnnouncementsInstructor = new RoundedFlowLayoutPanel();
            picAnnouncementsInstructor = new PictureBox();
            lblAnnouncementsText = new Label();
            flpCalendarInstructor = new RoundedFlowLayoutPanel();
            picCalendarInstructor = new PictureBox();
            lblCalendarText = new Label();
            flpNotesInstructor = new RoundedFlowLayoutPanel();
            picNotesInstructor = new PictureBox();
            lblNotesInstructor = new Label();
            flpAssistInstructor = new RoundedFlowLayoutPanel();
            picAssistInstructor = new PictureBox();
            lblAssistInstructor = new Label();
            lblAnnouncementDot = new Label();
            flpSettingsInstructor = new RoundedFlowLayoutPanel();
            picSettingsInstructor = new PictureBox();
            lblSettingsInstructor = new Label();
            shell = new CustomPanel();
            cPanelSideBarInstructor = new TranslucentSidebarPanel();
            flpLogoInstructor = new FlowLayoutPanel();
            picLogoInstructor = new PictureBox();
            InstructorTitlePanel = new Panel();
            profile = new CustomPanel();
            pbProfile = new PictureBox();
            profileNameLabel = new Label();
            content = new CustomPanel();
            courseCards = new RoundedFlowLayoutPanel();
            lblSMARTInstructor = new Label();
            lblInstructorPanel = new Label();
            topDivider = new CustomPanel();
            bottomDivider = new CustomPanel();
            flpDashboardInstructor = new RoundedFlowLayoutPanel();
            picDashboardInstructor = new PictureBox();
            lblDashboardInstructor = new Label();
            flpSignOutInstructor = new RoundedFlowLayoutPanel();
            picSignOutInstructor = new PictureBox();
            lblSignOutInstructor = new Label();
            lblWelcomeInstructor = new Label();
            lblCurr = new Label();
            cPnlCourseHolder = new CustomPanel();
            lblCourse = new Label();
            lblCourseName = new Label();
            lblCourseCode = new Label();
            lblCourseDetails = new Label();
            lblCourseStudents = new Label();
            lblCourseOpen = new Label();

            shell.SuspendLayout();
            cPanelSideBarInstructor.SuspendLayout();
            flpLogoInstructor.SuspendLayout();
            InstructorTitlePanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picLogoInstructor).BeginInit();
            profile.SuspendLayout();
            content.SuspendLayout();
            courseCards.SuspendLayout();
            cPnlCourseHolder.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pbProfile).BeginInit();
            flpDashboardInstructor.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picDashboardInstructor).BeginInit();
            flpSignOutInstructor.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picSignOutInstructor).BeginInit();
            flpSettingsInstructor.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picSettingsInstructor).BeginInit();
            SuspendLayout();
            // shell
            shell.Name = "shell";
            shell.Dock = DockStyle.Fill;
            shell.BackColor = Color.FromArgb(13, 17, 38);
            shell.BorderWidth = 0;
            shell.CornerRadius = 1;
            // cPanelSideBarInstructor
            cPanelSideBarInstructor.Name = "cPanelSideBarInstructor";
            cPanelSideBarInstructor.Dock = DockStyle.Left;
            cPanelSideBarInstructor.Size = new Size(226, 845);
            cPanelSideBarInstructor.BackColor = Color.FromArgb(22, 33, 62);
            cPanelSideBarInstructor.Padding = new Padding(12, 12, 14, 14);
            cPanelSideBarInstructor.BorderWidth = 0;
            cPanelSideBarInstructor.CornerRadius = 1;
            // flpLogoInstructor
            //
            flpLogoInstructor.Controls.Add(picLogoInstructor);
            flpLogoInstructor.Controls.Add(InstructorTitlePanel);
            flpLogoInstructor.Dock = DockStyle.Top;
            flpLogoInstructor.Location = new Point(12, 12);
            flpLogoInstructor.Name = "flpLogoInstructor";
            flpLogoInstructor.Size = new Size(200, 75);
            flpLogoInstructor.TabIndex = 1;
            flpLogoInstructor.WrapContents = false;
            //
            // picLogoInstructor
            //
            picLogoInstructor.Anchor = AnchorStyles.None;
            picLogoInstructor.BackgroundImage = (Image)resources.GetObject("picLogoInstructor.BackgroundImage");
            picLogoInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picLogoInstructor.Location = new Point(3, 15);
            picLogoInstructor.Name = "picLogoInstructor";
            picLogoInstructor.Size = new Size(50, 50);
            picLogoInstructor.TabIndex = 1;
            picLogoInstructor.TabStop = false;
            //
            // InstructorTitlePanel
            //
            InstructorTitlePanel.BackColor = Color.FromArgb(22, 33, 62);
            InstructorTitlePanel.Controls.Add(lblSMARTInstructor);
            InstructorTitlePanel.Controls.Add(lblInstructorPanel);
            InstructorTitlePanel.Location = new Point(59, 3);
            InstructorTitlePanel.Name = "InstructorTitlePanel";
            InstructorTitlePanel.Size = new Size(141, 75);
            InstructorTitlePanel.TabIndex = 1;
            //
            // lblSMARTInstructor
            //
            lblSMARTInstructor.Anchor = AnchorStyles.None;
            lblSMARTInstructor.AutoSize = true;
            lblSMARTInstructor.Font = new Font("Bahnschrift", 22F, FontStyle.Bold);
            lblSMARTInstructor.ForeColor = Color.FromArgb(233, 69, 96);
            lblSMARTInstructor.Location = new Point(3, 0);
            lblSMARTInstructor.Name = "lblSMARTInstructor";
            lblSMARTInstructor.Size = new Size(135, 36);
            lblSMARTInstructor.TabIndex = 1;
            lblSMARTInstructor.Text = "S.M.A.R.T";
            lblSMARTInstructor.TextAlign = ContentAlignment.MiddleCenter;
            //
            // lblInstructorPanel
            //
            lblInstructorPanel.Anchor = AnchorStyles.None;
            lblInstructorPanel.Font = new Font("Bahnschrift Light", 10.2F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lblInstructorPanel.ForeColor = Color.White;
            lblInstructorPanel.Location = new Point(3, 36);
            lblInstructorPanel.Name = "lblInstructorPanel";
            lblInstructorPanel.Size = new Size(135, 23);
            lblInstructorPanel.TabIndex = 1;
            lblInstructorPanel.Text = "Instructor Panel";
            lblInstructorPanel.TextAlign = ContentAlignment.MiddleCenter;
            //
            // profile
            profile.Name = "profile";
            profile.Dock = DockStyle.Top;
            profile.Height = 50;
            profile.BackColor = Color.FromArgb(22, 33, 62);
            profile.BorderWidth = 0;
            profile.CornerRadius = 1;
            profile.Padding = new Padding(8);
            // pbProfile
            pbProfile.Name = "pbProfile";
            pbProfile.Size = new Size(40, 40);
            pbProfile.BackColor = Color.FromArgb(22, 33, 62);
            pbProfile.SizeMode = PictureBoxSizeMode.Zoom;
            pbProfile.Location = new Point(8, 5);
            // profileNameLabel
            profileNameLabel.Name = "profileNameLabel";
            profileNameLabel.Text = "Instructor";
            profileNameLabel.ForeColor = Color.White;
            profileNameLabel.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            profileNameLabel.AutoEllipsis = false;
            profileNameLabel.UseMnemonic = false;
            profileNameLabel.TextAlign = ContentAlignment.MiddleLeft;
            profileNameLabel.Location = new Point(56, 15);
            profileNameLabel.Size = new Size(136, 20);
            profileNameLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            // content
            content.Name = "content";
            content.Dock = DockStyle.Fill;
            content.BackColor = Color.FromArgb(13, 17, 38);
            content.Padding = new Padding(32);
            content.BorderWidth = 0;
            content.CornerRadius = 1;
            // courseCards
            courseCards.Name = "courseCards";
            courseCards.Dock = DockStyle.Fill;
            courseCards.AutoScroll = true;
            courseCards.WrapContents = true;
            courseCards.BackColor = Color.FromArgb(13, 17, 38);
            courseCards.Padding = new Padding(0, 12, 12, 12);
            courseCards.BorderSize = 0;
            courseCards.BorderRadius = 0;
            // topDivider
            topDivider.Name = "topDivider";
            topDivider.Dock = DockStyle.Top;
            topDivider.Height = 1;
            topDivider.BackColor = Color.FromArgb(65, 75, 100);
            topDivider.BorderWidth = 0;
            topDivider.CornerRadius = 1;
            topDivider.Margin = new Padding(0, 4, 0, 12);
            // bottomDivider
            bottomDivider.Name = "bottomDivider";
            bottomDivider.Dock = DockStyle.Top;
            bottomDivider.Height = 1;
            bottomDivider.BackColor = Color.FromArgb(65, 75, 100);
            bottomDivider.BorderWidth = 0;
            bottomDivider.CornerRadius = 1;
            bottomDivider.Margin = new Padding(0, 4, 0, 12);
            // flpDashboardInstructor
            //
            flpDashboardInstructor.BorderColor = Color.Transparent;
            flpDashboardInstructor.BorderRadius = 5;
            flpDashboardInstructor.BorderSize = 1;
            flpDashboardInstructor.Controls.Add(picDashboardInstructor);
            flpDashboardInstructor.Controls.Add(lblDashboardInstructor);
            flpDashboardInstructor.Dock = DockStyle.Top;
            flpDashboardInstructor.BackColor = Color.FromArgb(233, 69, 96);
            flpDashboardInstructor.Cursor = Cursors.Hand;
            flpDashboardInstructor.Name = "flpDashboardInstructor";
            flpDashboardInstructor.Padding = new Padding(4, 0, 0, 0);
            flpDashboardInstructor.Size = new Size(177, 40);
            flpDashboardInstructor.TabIndex = 0;
            flpDashboardInstructor.WrapContents = false;
            //
            // picDashboardInstructor
            //
            picDashboardInstructor.BackgroundImage = (Image)resources.GetObject("picDashboardInstructor.BackgroundImage");
            picDashboardInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picDashboardInstructor.Location = new Point(7, 3);
            picDashboardInstructor.Name = "picDashboardInstructor";
            picDashboardInstructor.Size = new Size(30, 30);
            picDashboardInstructor.TabIndex = 0;
            picDashboardInstructor.TabStop = false;
            //
            // lblDashboardInstructor
            //
            lblDashboardInstructor.Anchor = AnchorStyles.None;
            lblDashboardInstructor.Font = new Font("Bahnschrift", 10F);
            lblDashboardInstructor.ForeColor = Color.White;
            lblDashboardInstructor.Location = new Point(43, 6);
            lblDashboardInstructor.Name = "lblDashboardInstructor";
            lblDashboardInstructor.Size = new Size(81, 23);
            lblDashboardInstructor.TabIndex = 2;
            lblDashboardInstructor.Text = "Dashboard";
            lblDashboardInstructor.TextAlign = ContentAlignment.MiddleLeft;
            //
            // flpSettingsInstructor
            flpSettingsInstructor.Name = "flpSettingsInstructor";
            flpSettingsInstructor.BackColor = Color.FromArgb(22, 33, 62);
            flpSettingsInstructor.BorderColor = Color.Transparent;
            flpSettingsInstructor.BorderRadius = 6;
            flpSettingsInstructor.Dock = DockStyle.Bottom;
            flpSettingsInstructor.Size = new Size(177, 42);
            flpSettingsInstructor.Padding = new Padding(8, 0, 0, 0);
            flpSettingsInstructor.WrapContents = false;
            flpSettingsInstructor.Cursor = Cursors.Hand;
            flpSettingsInstructor.Controls.Add(picSettingsInstructor);
            flpSettingsInstructor.Controls.Add(lblSettingsInstructor);
            // picSettingsInstructor
            picSettingsInstructor.Name = "picSettingsInstructor";
            picSettingsInstructor.BackgroundImage = (Image)resources.GetObject("picSettingsInstructor.BackgroundImage");
            picSettingsInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picSettingsInstructor.Size = new Size(24, 24);
            picSettingsInstructor.Margin = new Padding(0, 9, 8, 9);
            picSettingsInstructor.TabStop = false;
            picSettingsInstructor.Cursor = Cursors.Hand;
            // lblSettingsInstructor
            lblSettingsInstructor.Name = "lblSettingsInstructor";
            lblSettingsInstructor.Text = "Settings";
            lblSettingsInstructor.ForeColor = Color.White;
            lblSettingsInstructor.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            lblSettingsInstructor.Size = new Size(120, 42);
            lblSettingsInstructor.Margin = Padding.Empty;
            lblSettingsInstructor.TextAlign = ContentAlignment.MiddleLeft;
            lblSettingsInstructor.Cursor = Cursors.Hand;
            // flpSignOutInstructor
            flpSignOutInstructor.Name = "flpSignOutInstructor";
            flpSignOutInstructor.BackColor = Color.FromArgb(22, 33, 62);
            flpSignOutInstructor.BorderColor = Color.Transparent;
            flpSignOutInstructor.BorderRadius = 5;
            flpSignOutInstructor.Dock = DockStyle.Bottom;
            flpSignOutInstructor.Size = new Size(177, 40);
            flpSignOutInstructor.Padding = new Padding(4, 0, 0, 0);
            flpSignOutInstructor.WrapContents = false;
            flpSignOutInstructor.Cursor = Cursors.Hand;
            flpSignOutInstructor.Controls.Add(picSignOutInstructor);
            flpSignOutInstructor.Controls.Add(lblSignOutInstructor);
            // picSignOutInstructor
            picSignOutInstructor.Name = "picSignOutInstructor";
            picSignOutInstructor.BackgroundImage = (Image)resources.GetObject("picSignOutInstructor.BackgroundImage");
            picSignOutInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picSignOutInstructor.Size = new Size(30, 30);
            picSignOutInstructor.TabStop = false;
            picSignOutInstructor.Cursor = Cursors.Hand;
            // lblSignOutInstructor
            lblSignOutInstructor.Name = "lblSignOutInstructor";
            lblSignOutInstructor.Anchor = AnchorStyles.None;
            lblSignOutInstructor.Text = "Sign Out";
            lblSignOutInstructor.Font = new Font("Bahnschrift", 10F);
            lblSignOutInstructor.ForeColor = Color.White;
            lblSignOutInstructor.Size = new Size(120, 23);
            lblSignOutInstructor.TextAlign = ContentAlignment.MiddleLeft;
            lblSignOutInstructor.Cursor = Cursors.Hand;
            // lblWelcomeInstructor
            lblWelcomeInstructor.Name = "lblWelcomeInstructor";
            lblWelcomeInstructor.Text = "Welcome, Instructor!";
            lblWelcomeInstructor.Dock = DockStyle.Top;
            lblWelcomeInstructor.Height = 48;
            lblWelcomeInstructor.ForeColor = Color.White;
            lblWelcomeInstructor.Font = new Font("Segoe UI", 22F, FontStyle.Bold);
            // lblCurr
            lblCurr.Name = "lblCurr";
            lblCurr.Text = "Here are your current courses.";
            lblCurr.Dock = DockStyle.Top;
            lblCurr.Height = 30;
            lblCurr.ForeColor = Color.FromArgb(150, 150, 170);
            lblCurr.Font = new Font("Segoe UI", 11F);
            // cPnlCourseHolder
            cPnlCourseHolder.Name = "cPnlCourseHolder";
            cPnlCourseHolder.Size = new Size(220, 200);
            cPnlCourseHolder.BackColor = Color.FromArgb(22, 33, 62);
            cPnlCourseHolder.BorderColor = Color.FromArgb(233, 69, 96);
            cPnlCourseHolder.BorderWidth = 2;
            cPnlCourseHolder.CornerRadius = 12;
            cPnlCourseHolder.Margin = new Padding(0, 4, 18, 18);
            cPnlCourseHolder.Padding = new Padding(14);
            // lblCourse
            lblCourse.Name = "lblCourse";
            lblCourse.Text = "COURSE101";
            lblCourse.Dock = DockStyle.Top;
            lblCourse.Height = 30;
            lblCourse.ForeColor = Color.FromArgb(233, 69, 96);
            lblCourse.Font = new Font("Segoe UI", 17F, FontStyle.Bold);
            lblCourse.AutoEllipsis = true;
            lblCourse.TextAlign = ContentAlignment.MiddleLeft;
            // lblCourseName
            lblCourseName.Name = "lblCourseName";
            lblCourseName.Text = "Course name";
            lblCourseName.Dock = DockStyle.Top;
            lblCourseName.Height = 38;
            lblCourseName.ForeColor = Color.White;
            lblCourseName.Font = new Font("Segoe UI", 11F, FontStyle.Regular);
            lblCourseName.AutoEllipsis = true;
            lblCourseName.TextAlign = ContentAlignment.MiddleLeft;
            // lblCourseCode
            lblCourseCode.Name = "lblCourseCode";
            lblCourseCode.Text = "Code: 0000";
            lblCourseCode.Dock = DockStyle.Top;
            lblCourseCode.Height = 22;
            lblCourseCode.ForeColor = Color.FromArgb(150, 150, 170);
            lblCourseCode.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
            lblCourseCode.AutoEllipsis = true;
            lblCourseCode.TextAlign = ContentAlignment.MiddleLeft;
            // lblCourseDetails
            lblCourseDetails.Name = "lblCourseDetails";
            lblCourseDetails.Text = "Schedule | Days\nRoom · Term · Program";
            lblCourseDetails.Dock = DockStyle.Top;
            lblCourseDetails.Height = 52;
            lblCourseDetails.ForeColor = Color.FromArgb(150, 150, 170);
            lblCourseDetails.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
            lblCourseDetails.AutoEllipsis = true;
            lblCourseDetails.TextAlign = ContentAlignment.MiddleLeft;
            // lblCourseStudents
            lblCourseStudents.Name = "lblCourseStudents";
            lblCourseStudents.Text = "👥 0 Students";
            lblCourseStudents.Dock = DockStyle.Top;
            lblCourseStudents.Height = 25;
            lblCourseStudents.ForeColor = Color.FromArgb(150, 150, 170);
            lblCourseStudents.Font = new Font("Segoe UI", 10F, FontStyle.Regular);
            lblCourseStudents.AutoEllipsis = true;
            lblCourseStudents.TextAlign = ContentAlignment.MiddleLeft;
            // lblCourseOpen
            lblCourseOpen.Name = "lblCourseOpen";
            lblCourseOpen.Text = "Click to open →";
            lblCourseOpen.Dock = DockStyle.Top;
            lblCourseOpen.Height = 20;
            lblCourseOpen.ForeColor = Color.FromArgb(233, 69, 96);
            lblCourseOpen.Font = new Font("Segoe UI", 9F, FontStyle.Regular);
            lblCourseOpen.AutoEllipsis = true;
            lblCourseOpen.TextAlign = ContentAlignment.MiddleLeft;
            flpScheduleInstructor.Name = "flpScheduleInstructor";
            flpScheduleInstructor.BackColor = Color.FromArgb(22, 33, 62);
            flpScheduleInstructor.BorderColor = Color.Transparent;
            flpScheduleInstructor.BorderRadius = 5;
            flpScheduleInstructor.BorderSize = 1;
            flpScheduleInstructor.Padding = new Padding(4, 0, 0, 0);
            flpScheduleInstructor.Location = new Point(12, 184);
            flpScheduleInstructor.Size = new Size(200, 40);
            flpScheduleInstructor.WrapContents = false;
            flpScheduleInstructor.Cursor = Cursors.Hand;
            flpScheduleInstructor.Controls.Add(picScheduleInstructor);
            flpScheduleInstructor.Controls.Add(lblScheduleInstructor);
            picScheduleInstructor.Name = "picScheduleInstructor";
            picScheduleInstructor.BackgroundImage = (Image)resources.GetObject("picScheduleInstructor.BackgroundImage");
            picScheduleInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picScheduleInstructor.Size = new Size(30, 30);
            picScheduleInstructor.BackColor = Color.Transparent;
            picScheduleInstructor.TabStop = false;
            picScheduleInstructor.Cursor = Cursors.Hand;
            lblScheduleInstructor.Name = "lblScheduleInstructor";
            lblScheduleInstructor.Text = "Schedule";
            lblScheduleInstructor.Font = new Font("Bahnschrift", 10F);
            lblScheduleInstructor.ForeColor = Color.White;
            lblScheduleInstructor.BackColor = Color.Transparent;
            lblScheduleInstructor.Anchor = AnchorStyles.None;
            lblScheduleInstructor.Size = new Size(135, 23);
            lblScheduleInstructor.TextAlign = ContentAlignment.MiddleLeft;
            lblScheduleInstructor.Cursor = Cursors.Hand;
            flpScheduleInstructor.Click += Schedule_Click;
            picScheduleInstructor.Click += Schedule_Click;
            lblScheduleInstructor.Click += Schedule_Click;
            flpAnnouncementsInstructor.Name = "flpAnnouncementsInstructor";
            flpAnnouncementsInstructor.BackColor = Color.FromArgb(22, 33, 62);
            flpAnnouncementsInstructor.BorderColor = Color.Transparent;
            flpAnnouncementsInstructor.BorderRadius = 5;
            flpAnnouncementsInstructor.BorderSize = 1;
            flpAnnouncementsInstructor.Padding = new Padding(4, 0, 0, 0);
            flpAnnouncementsInstructor.Location = new Point(12, 229);
            flpAnnouncementsInstructor.Size = new Size(200, 40);
            flpAnnouncementsInstructor.WrapContents = false;
            flpAnnouncementsInstructor.Cursor = Cursors.Hand;
            flpAnnouncementsInstructor.Controls.Add(picAnnouncementsInstructor);
            flpAnnouncementsInstructor.Controls.Add(lblAnnouncementsText);
            picAnnouncementsInstructor.Name = "picAnnouncementsInstructor";
            picAnnouncementsInstructor.BackgroundImage = (Image)resources.GetObject("picAnnouncementsInstructor.BackgroundImage");
            picAnnouncementsInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picAnnouncementsInstructor.Size = new Size(30, 30);
            picAnnouncementsInstructor.BackColor = Color.Transparent;
            picAnnouncementsInstructor.TabStop = false;
            picAnnouncementsInstructor.Cursor = Cursors.Hand;
            lblAnnouncementsText.Name = "lblAnnouncementsText";
            lblAnnouncementsText.Text = "Announcements";
            lblAnnouncementsText.Font = new Font("Bahnschrift", 10F);
            lblAnnouncementsText.ForeColor = Color.White;
            lblAnnouncementsText.BackColor = Color.Transparent;
            lblAnnouncementsText.Anchor = AnchorStyles.None;
            lblAnnouncementsText.Size = new Size(135, 23);
            lblAnnouncementsText.TextAlign = ContentAlignment.MiddleLeft;
            lblAnnouncementsText.Cursor = Cursors.Hand;
            flpAnnouncementsInstructor.Click += Announcements_Click;
            picAnnouncementsInstructor.Click += Announcements_Click;
            lblAnnouncementsText.Click += Announcements_Click;
            flpCalendarInstructor.Name = "flpCalendarInstructor";
            flpCalendarInstructor.BackColor = Color.FromArgb(22, 33, 62);
            flpCalendarInstructor.BorderColor = Color.Transparent;
            flpCalendarInstructor.BorderRadius = 5;
            flpCalendarInstructor.BorderSize = 1;
            flpCalendarInstructor.Padding = new Padding(4, 0, 0, 0);
            flpCalendarInstructor.Location = new Point(12, 274);
            flpCalendarInstructor.Size = new Size(200, 40);
            flpCalendarInstructor.WrapContents = false;
            flpCalendarInstructor.Cursor = Cursors.Hand;
            flpCalendarInstructor.Controls.Add(picCalendarInstructor);
            flpCalendarInstructor.Controls.Add(lblCalendarText);
            picCalendarInstructor.Name = "picCalendarInstructor";
            picCalendarInstructor.BackgroundImage = (Image)resources.GetObject("picCalendarInstructor.BackgroundImage");
            picCalendarInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picCalendarInstructor.Size = new Size(30, 30);
            picCalendarInstructor.BackColor = Color.Transparent;
            picCalendarInstructor.TabStop = false;
            picCalendarInstructor.Cursor = Cursors.Hand;
            lblCalendarText.Name = "lblCalendarText";
            lblCalendarText.Text = "Calendar";
            lblCalendarText.Font = new Font("Bahnschrift", 10F);
            lblCalendarText.ForeColor = Color.White;
            lblCalendarText.BackColor = Color.Transparent;
            lblCalendarText.Anchor = AnchorStyles.None;
            lblCalendarText.Size = new Size(135, 23);
            lblCalendarText.TextAlign = ContentAlignment.MiddleLeft;
            lblCalendarText.Cursor = Cursors.Hand;
            flpCalendarInstructor.Click += Calendar_Click;
            picCalendarInstructor.Click += Calendar_Click;
            lblCalendarText.Click += Calendar_Click;
            flpNotesInstructor.Name = "flpNotesInstructor";
            flpNotesInstructor.BackColor = Color.FromArgb(22, 33, 62);
            flpNotesInstructor.BorderColor = Color.Transparent;
            flpNotesInstructor.BorderRadius = 5;
            flpNotesInstructor.BorderSize = 1;
            flpNotesInstructor.Padding = new Padding(4, 0, 0, 0);
            flpNotesInstructor.Location = new Point(12, 319);
            flpNotesInstructor.Size = new Size(200, 40);
            flpNotesInstructor.WrapContents = false;
            flpNotesInstructor.Cursor = Cursors.Hand;
            flpNotesInstructor.Controls.Add(picNotesInstructor);
            flpNotesInstructor.Controls.Add(lblNotesInstructor);
            picNotesInstructor.Name = "picNotesInstructor";
            picNotesInstructor.BackgroundImage = (Image)resources.GetObject("picNotesInstructor.BackgroundImage");
            picNotesInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picNotesInstructor.Size = new Size(30, 30);
            picNotesInstructor.BackColor = Color.Transparent;
            picNotesInstructor.TabStop = false;
            picNotesInstructor.Cursor = Cursors.Hand;
            lblNotesInstructor.Name = "lblNotesInstructor";
            lblNotesInstructor.Text = "Notes";
            lblNotesInstructor.Font = new Font("Bahnschrift", 10F);
            lblNotesInstructor.ForeColor = Color.White;
            lblNotesInstructor.BackColor = Color.Transparent;
            lblNotesInstructor.Anchor = AnchorStyles.None;
            lblNotesInstructor.Size = new Size(135, 23);
            lblNotesInstructor.TextAlign = ContentAlignment.MiddleLeft;
            lblNotesInstructor.Cursor = Cursors.Hand;
            flpNotesInstructor.Click += Notes_Click;
            picNotesInstructor.Click += Notes_Click;
            lblNotesInstructor.Click += Notes_Click;
            flpAssistInstructor.Name = "flpAssistInstructor";
            flpAssistInstructor.BackColor = Color.FromArgb(22, 33, 62);
            flpAssistInstructor.BorderColor = Color.Transparent;
            flpAssistInstructor.BorderRadius = 5;
            flpAssistInstructor.BorderSize = 1;
            flpAssistInstructor.Padding = new Padding(4, 0, 0, 0);
            flpAssistInstructor.Location = new Point(12, 364);
            flpAssistInstructor.Size = new Size(200, 40);
            flpAssistInstructor.WrapContents = false;
            flpAssistInstructor.Cursor = Cursors.Hand;
            flpAssistInstructor.Controls.Add(picAssistInstructor);
            flpAssistInstructor.Controls.Add(lblAssistInstructor);
            picAssistInstructor.Name = "picAssistInstructor";
            picAssistInstructor.BackgroundImage = (Image)resources.GetObject("picAssistInstructor.BackgroundImage");
            picAssistInstructor.BackgroundImageLayout = ImageLayout.Zoom;
            picAssistInstructor.Size = new Size(30, 30);
            picAssistInstructor.BackColor = Color.Transparent;
            picAssistInstructor.TabStop = false;
            picAssistInstructor.Cursor = Cursors.Hand;
            lblAssistInstructor.Name = "lblAssistInstructor";
            lblAssistInstructor.Text = "Assist";
            lblAssistInstructor.Font = new Font("Bahnschrift", 10F);
            lblAssistInstructor.ForeColor = Color.White;
            lblAssistInstructor.BackColor = Color.Transparent;
            lblAssistInstructor.Anchor = AnchorStyles.None;
            lblAssistInstructor.Size = new Size(135, 23);
            lblAssistInstructor.TextAlign = ContentAlignment.MiddleLeft;
            lblAssistInstructor.Cursor = Cursors.Hand;
            flpAssistInstructor.Click += Assist_Click;
            picAssistInstructor.Click += Assist_Click;
            lblAssistInstructor.Click += Assist_Click;
            lblAnnouncementDot.Name = "lblAnnouncementDot";
            lblAnnouncementDot.Text = "●";
            lblAnnouncementDot.Size = new Size(14, 26);
            lblAnnouncementDot.Margin = Padding.Empty;
            lblAnnouncementDot.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
            lblAnnouncementDot.ForeColor = Color.FromArgb(233, 69, 96);
            lblAnnouncementDot.BackColor = Color.Transparent;
            lblAnnouncementDot.Visible = false;
            lblAnnouncementDot.Click += Announcements_Click;
            flpAnnouncementsInstructor.Controls.Add(lblAnnouncementDot);
            profile.Controls.Add(pbProfile);
            profile.Controls.Add(profileNameLabel);
            cPanelSideBarInstructor.Controls.Add(flpScheduleInstructor);
            cPanelSideBarInstructor.Controls.Add(flpAnnouncementsInstructor);
            cPanelSideBarInstructor.Controls.Add(flpCalendarInstructor);
            cPanelSideBarInstructor.Controls.Add(flpNotesInstructor);
            cPanelSideBarInstructor.Controls.Add(flpAssistInstructor);
            cPanelSideBarInstructor.Controls.Add(flpSettingsInstructor);
            cPanelSideBarInstructor.Controls.Add(flpSignOutInstructor);
            cPanelSideBarInstructor.Controls.Add(flpDashboardInstructor);
            cPanelSideBarInstructor.Controls.Add(bottomDivider);
            cPanelSideBarInstructor.Controls.Add(profile);
            cPanelSideBarInstructor.Controls.Add(topDivider);
            cPanelSideBarInstructor.Controls.Add(flpLogoInstructor);
            shell.Controls.Add(content);
            shell.Controls.Add(cPanelSideBarInstructor);
            BackgroundImage = (Image)resources.GetObject("InstructorBackground.Image");
            BackgroundImageLayout = ImageLayout.Stretch;
            shell.BackgroundImage = BackgroundImage;
            shell.BackgroundImageLayout = ImageLayout.Stretch;
            shell.BackColor = Color.Transparent;
            content.BackColor = Color.Transparent;
            Controls.Add(shell);
            content.Controls.Add(courseCards);
            content.Controls.Add(lblCurr);
            content.Controls.Add(lblWelcomeInstructor);
            courseCards.Controls.Add(cPnlCourseHolder);
            cPnlCourseHolder.Controls.Add(lblCourseOpen);
            cPnlCourseHolder.Controls.Add(lblCourseStudents);
            cPnlCourseHolder.Controls.Add(lblCourseDetails);
            cPnlCourseHolder.Controls.Add(lblCourseCode);
            cPnlCourseHolder.Controls.Add(lblCourseName);
            cPnlCourseHolder.Controls.Add(lblCourse);


            flpDashboardInstructor.Click += Dashboard_Click;
            picDashboardInstructor.Click += Dashboard_Click;
            lblDashboardInstructor.Click += Dashboard_Click;
            picDashboardInstructor.Cursor = Cursors.Hand;
            lblDashboardInstructor.Cursor = Cursors.Hand;
            flpSignOutInstructor.Click += SignOut_Click;
            picSignOutInstructor.Click += SignOut_Click;
            lblSignOutInstructor.Click += SignOut_Click;
            pbProfile.Paint += Profile_Paint;
            profile.SizeChanged += ProfileLayout_Changed;
            pbProfile.SizeChanged += ProfileLayout_Changed;
            profileNameLabel.TextChanged += ProfileLayout_Changed;
            profileNameLabel.FontChanged += ProfileLayout_Changed;
            flpSettingsInstructor.Click += Settings_Click;
            picSettingsInstructor.Click += Settings_Click;
            lblSettingsInstructor.Click += Settings_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(13, 17, 38);
            ClientSize = new Size(1540, 845);
            FormBorderStyle = FormBorderStyle.Sizable;
            MinimumSize = new Size(900, 600);
            Name = "InstructorUI";
            Text = "InstructorUI";
            WindowState = FormWindowState.Maximized;
            flpDashboardInstructor.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picDashboardInstructor).EndInit();
            flpSignOutInstructor.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picSignOutInstructor).EndInit();
            flpSettingsInstructor.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)picSettingsInstructor).EndInit();
            shell.ResumeLayout(false);
            cPanelSideBarInstructor.ResumeLayout(false);
            flpLogoInstructor.ResumeLayout(false);
            InstructorTitlePanel.ResumeLayout(false);
            InstructorTitlePanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)picLogoInstructor).EndInit();
            profile.ResumeLayout(false);
            content.ResumeLayout(false);
            courseCards.ResumeLayout(false);
            cPnlCourseHolder.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pbProfile).EndInit();
            ResumeLayout(false);
        }
        #endregion
        private CustomPanel shell;
        private TranslucentSidebarPanel cPanelSideBarInstructor;
        private RoundedFlowLayoutPanel flpScheduleInstructor;
        private PictureBox picScheduleInstructor;
        private Label lblScheduleInstructor;
        private RoundedFlowLayoutPanel flpAnnouncementsInstructor;
        private PictureBox picAnnouncementsInstructor;
        private Label lblAnnouncementsText;
        private RoundedFlowLayoutPanel flpCalendarInstructor;
        private PictureBox picCalendarInstructor;
        private Label lblCalendarText;
        private RoundedFlowLayoutPanel flpNotesInstructor;
        private PictureBox picNotesInstructor;
        private Label lblNotesInstructor;
        private RoundedFlowLayoutPanel flpAssistInstructor;
        private PictureBox picAssistInstructor;
        private Label lblAssistInstructor;
        private Label lblAnnouncementDot;
        private FlowLayoutPanel flpLogoInstructor;
        private PictureBox picLogoInstructor;
        private Panel InstructorTitlePanel;
        private CustomPanel profile;
        private PictureBox pbProfile;
        private Label profileNameLabel;
        private CustomPanel content;
        private RoundedFlowLayoutPanel courseCards;
        private Label lblSMARTInstructor;
        private Label lblInstructorPanel;
        private CustomPanel topDivider;
        private CustomPanel bottomDivider;
        private RoundedFlowLayoutPanel flpDashboardInstructor;
        private PictureBox picDashboardInstructor;
        private Label lblDashboardInstructor;
        private RoundedFlowLayoutPanel flpSignOutInstructor;
        private PictureBox picSignOutInstructor;
        private Label lblSignOutInstructor;
        private RoundedFlowLayoutPanel flpSettingsInstructor;
        private PictureBox picSettingsInstructor;
        private Label lblSettingsInstructor;
        private Label lblWelcomeInstructor;
        private Label lblCurr;
        private CustomPanel cPnlCourseHolder;
        private Label lblCourse;
        private Label lblCourseName;
        private Label lblCourseCode;
        private Label lblCourseDetails;
        private Label lblCourseStudents;
        private Label lblCourseOpen;

    }
}
