<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Form1.cs" />
    <Compile Remove="Form1.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Form1.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Krypton.Toolkit" Version="105.26.7.201" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="ReaLTaiizor" Version="3.8.2.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Enrollment.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Enrollment.Designer.cs">
      <DependentUpon>Enrollment.cs</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
